### ISSUE TITLE
addsms: 500 Internal Server Error

### ISSUE THREAD

**Issue by komputronika** [smsgateway24/smsgateway24-php-sdk#2]
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST https://smsgateway24.com/getdata/addsms` resulted in a `500 Internal Server Error` response:
    <!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" /><script type="text/javascript">(window.NREUM||(NRE (truncated...)

**Comment by smsgateway24** [comment]
Hello!

Can you please provide request body.

**Comment by smsgateway24** [comment]
Looks like request was with wrong vars.
