### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by rolaksy** [smsgateway24/smsgateway24-php-sdk#3]
Hi, 
while getting composer require smsgateway24/smsgateway24-php-sdk, I am getting below error.

**my composer json**
`"require": {
        "php": "^7.3",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^8.0",
        "laravel/tinker": "^2.0"
    },`

**Error**
Using version ^1.4 for smsgateway24/smsgateway24-php-sdk
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[7.2.0, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - smsgateway24/smsgateway24-php-sdk v1.4 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Installation request for smsgateway24/smsgateway24-php-sdk ^1.4 -> satisfiable by smsgateway24/smsgateway24-php-sdk[v1.4].
    - Installation request for guzzlehttp/guzzle ^7.2 -> satisfiable by guzzlehttp/guzzle[7.2.0].

Installation failed, reverting ./composer.json to its original content.

When I downgrade  "guzzlehttp/guzzle": "^7.2", to version 6.0, it's working...

Can you please update your guzzlehttp/guzzle to latest version...

**Comment by underwear** [comment]
fixed in [version 1.5
](https://github.com/smsgateway24/smsgateway24-php-sdk/releases/tag/v1.5)

Try now again.
